site_name: MPS Extensions
theme: 'cinder'

# Project information
site_description: Extensions and utilities for MPS
site_url: https://jetbrains.github.io/MPS-extensions/

# Repository

repo_url: https://github.com/jetbrains/mps-extensions

nav:
- Home: index.md
- Building: building.md
- Contributing: contributing.md
- Migrating: Migrating.md
- Adding: adding.md
- Extensions:
  - Full Extension List: extensions/all.md
  - Base Language Extensions:
      - Structure Check: extensions/bl-extensions/structure-check.md
      - Base Language Util (blutil): extensions/bl-extensions/blutil.md
  - Editor:
      - Cell Layout: extensions/editor/celllayout.md
      - Conditional Editor: extensions/editor/conditional-editor.md
      - Diagrams: extensions/editor/diagrams.md
      - Grammar Cells: extensions/editor/grammar-cells.md
      - Math: extensions/editor/math.md
      - Intentions for custom selections: extensions/editor/mouse-selection.md
      - Multiline: extensions/editor/multiline.md
      - Query List: extensions/editor/querylist.md
      - Richtext: extensions/editor/richtext.md
      - Tables: extensions/editor/tables.md
      - Tree Notation: extensions/editor/tree-notation.md
      - Widgets: extensions/editor/widgets.md
  - Generator:
      - Plaintext Generator: extensions/generator/plaintext-gen.md
  - Other:
      - Language Visualizer: extensions/other/langvis.md
      - Project View: extensions/other/project-view.md
      - Shadow Models: extensions/other/shadow-models.md
  - Stubs: extensions/stubs.md
  - Utilities:
      - Intentions Menu: extensions/utils/intentions-menu.md
      - Model Listener: extensions/utils/model-listener.md
      - Hacks: extensions/utils/hacks.md
      - Model Merger: extensions/utils/model-merger.md
      - Node Versioning: extensions/utils/node-versioning.md
      - Serializer: extensions/utils/serializer.md
  