site_name: MPS Extensions
theme: 'cinder'

# Project information
site_description: Extensions and utilities for MPS
site_url: https://jetbrains.github.io/MPS-extensions/

# Repository

repo_url: https://github.com/jetbrains/mps-extensions

nav:
- Home: index.md
- Building: building.md
- Contributing: contributing.md
- Migrating: Migrating.md
- Extensions:
  - Diagrams: extensions/diagrams.md
  - Node Versioning: extensions/node-versioning.md
  - Plaintext Generator: extensions/plaintext-gen.md
  - Shadow Models: extensions/shadowmodels.md
  - Language Visualizer: extensions/langvis.md
