site_name: MPS Extensions
theme:
  name: 'material'
  palette:
    - primary: blue grey
    - accent: indigo
  logo: assets/logo.png
  favicon: assets/favicon.png  
  features:
    - navigation.top
    - navigation.instant
    - navigation.tracking
    - navigation.expand
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.footer
    - header.autohide
    - content.code.annotate
    - search.suggest
    - search.highlight
    - search.share
    - announce.dismiss
    - content.code.copy
    - toc.integrate

site_description: MPS-extensions
site_url: https://jetbrains.github.io/MPS-extensions/

repo_url: https://github.com/jetbrains/mps-extensions
repo_name: mps-extensions

plugins:
  - search
  - autolinks
  - autolink_references:
      autolinks:
        - reference_prefix: MPS-
          target_url: https://youtrack.jetbrains.com/issue/MPS-<num>
        - reference_prefix: IDEABKL-
          target_url: https://youtrack.jetbrains.com/issue/IDEABKL-<num>
        - reference_prefix: JBR-
          target_url: https://youtrack.jetbrains.com/issue/JBR-<num>
        - reference_prefix: IDEA-
          target_url: https://youtrack.jetbrains.com/issue/IDEA-<num>
        - reference_prefix: IJSDK-
          target_url: https://youtrack.jetbrains.com/issue/IJSDK-<num>
        - reference_prefix: MPS_EXT-
          target_url: https://github.com/JetBrains/MPS-extensions/issues/<num>

markdown_extensions:
  - abbr
  - smarty
  - admonition
  - codehilite:
      guess_lang: false
  - footnotes
  - meta
  - def_list
  - toc:
      permalink: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.highlight:
      linenums: true
      anchor_linenums: true

  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.keys
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.mark
  - pymdownx.tilde
  - attr_list
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
  - md_in_html
  - pymdownx.magiclink:
      repo_url_shorthand: true
      social_url_shorthand: true
  - pymdownx.arithmatex:
      generic: true

nav:
- Home: https://jetbrains.github.io/MPS-extensions/
- Building: https://jetbrains.github.io/MPS-extensions/building
- Contributing: https://jetbrains.github.io/MPS-extensions/contributing
- Migrating: https://jetbrains.github.io/MPS-extensions/migrating
- Adding: https://jetbrains.github.io/MPS-extensions/adding
- Full Extension List: https://jetbrains.github.io/MPS-extensions/extensions/full_extensions_list
- Editor extensions:
    - Cell Layout: https://jetbrains.github.io/MPS-extensions/extensions/editor/celllayout
    - Conditional Editor: https://jetbrains.github.io/MPS-extensions/extensions/editor/conditional-editor
    - Diagrams: https://jetbrains.github.io/MPS-extensions/extensions/editor/diagrams
    - Grammar Cells: https://jetbrains.github.io/MPS-extensions/extensions/editor/grammar-cells
    - Math: https://jetbrains.github.io/MPS-extensions/extensions/editor/math
    - Intentions for custom selections: https://jetbrains.github.io/MPS-extensions/extensions/editor/mouse-selection
    - Multiline: https://jetbrains.github.io/MPS-extensions/extensions/editor/multiline
    - Query List: https://jetbrains.github.io/MPS-extensions/extensions/editor/querylist
    - Richtext: https://jetbrains.github.io/MPS-extensions/extensions/editor/richtext
    - Tables: https://jetbrains.github.io/MPS-extensions/extensions/editor/tables
    - Tree Notation: https://jetbrains.github.io/MPS-extensions/extensions/editor/tree-notation
    - Widgets: https://jetbrains.github.io/MPS-extensions/extensions/editor/widgets
- Other extensions:
  - Base Language Extensions:
      - Structure Check: https://jetbrains.github.io/MPS-extensions/extensions/bl-extensions/structure-check
      - Base Language Util (blutil): https://jetbrains.github.io/MPS-extensions/extensions/bl-extensions/blutil

  - Generator:
      - Plaintext Generator: https://jetbrains.github.io/MPS-extensions/extensions/generator/plaintext-gen
  - Other:
      - Language Visualizer: https://jetbrains.github.io/MPS-extensions/extensions/other/langvis
      - Project View: https://jetbrains.github.io/MPS-extensions/extensions/other/project-view
      - Shadow Models: https://jetbrains.github.io/MPS-extensions/extensions/other/shadow-models
  - Stubs: extensions/stubs
  - Utilities:
      - Intentions Menu: https://jetbrains.github.io/MPS-extensions/extensions/utils/intentions-menu
      - Model Listener: https://jetbrains.github.io/MPS-extensions/extensions/utils/model-listener
      - Hacks: https://jetbrains.github.io/MPS-extensions/extensions/utils/hacks
      - Model Merger: https://jetbrains.github.io/MPS-extensions/extensions/utils/model-merger
      - Node Versioning: https://jetbrains.github.io/MPS-extensions/extensions/utils/node-versioning
      - Serializer: https://jetbrains.github.io/MPS-extensions/extensions/utils/serializer

extra_css:
  - stylesheets/extra.css
  